name: End to End

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        dfx-version: ["0.16.1"]
        node: [20]

    steps:
      - uses: actions/checkout@v4

      - name: Setup rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: NPM install
        run: npm install

      - name: Setup dfx
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: ${{ matrix.dfx-version }}

      - name: Install dfx
        run: |
          dfx start --background

      - name: Build all canisters
        run: |
          dfx deploy
          dfx stop

      - name: Check Lint
        run: npm run lint

      - name: Run tests
        run: npm run test
        env:
          CI: true
          REPLICA_PORT: 8000
